### ISSUE TITLE
Make file column resizable 

### ISSUE THREAD

**Issue by WillItWork** [jasesmith/newton-dark-ui#2]
Right now the column uses a best fit width sizing. This is problematic with longer filenames. How feaible would it be to make this draggable, or alternatively, specify a max-width in theme settings?

**Comment by jasesmith** [comment]
I've noticed that as well. I will look into this when I have a chance. Since the theme uses an alternate set of styles to make a vertical tabs column, the tabs container proper may not have access to whatever lets the editor panel be resizable/draggable... but I don't know for sure yet.

A max-width setting is a good idea and will look into trying that. I made this theme so it would always shows the full filename as the default tabs orientation ellipsizes the file names which annoyed me greatly.

If a resizable tabs panel is not possible and a max-width setting will work, then the tabs column can be scrollable horizontally to expose the hidden tab text. Not perfect, but would be a solution for your issue and mine with the tabs panel.

**Comment by jasesmith** [comment]
I've added a resize to the tab column. This is low-level resize using CSS `resize: horizontal`. It works like the resize handle on an HTML `<textarea>` element. 

No theme setting yet to store a preferred width or maxWidth.

You should see a little orange triangle in the bottom-right corner of the tabs column:

![image](https://cloud.githubusercontent.com/assets/1619521/8584173/483176ae-2591-11e5-8bc1-a9be0923d658.png)
 _newton-dark-ui@v1.0.6_

Please let me know if this works for ya.

**Comment by WillItWork** [comment]
Jase:

This works pretty well! The dragging works very well as a peeking mechanism, but still allows me to allocate most of my horizontal to code.

Thank you for being so responsive.

**Comment by jasesmith** [comment]
I've needed this too but was just dealing with it. Sometimes when I need more horizontal space, a quick key combo `⌘\` (command + \) will toggle the file tree on or off.
